# Generated by Django 3.1.2 on 2023-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='duration',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='investment',
            name='endAt',
            field=models.DateTimeField(),
        ),
    ]
