# Generated by Django 3.1.2 on 2023-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230106_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
