# Generated by Django 3.1.2 on 2023-01-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230106_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
