# Generated by Django 3.1.2 on 2023-01-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230106_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
