# Generated by Django 3.1.2 on 2023-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230106_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
