# Generated by Django 3.1.2 on 2023-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230106_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dailyLimit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vidCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='watchAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
